import type { StockLocation } from '@prisma/client'

export type StockSeedRow = {
  name: string
  presentation?: string
  category: string
  supplier?: string
  supplierPhone?: string
  location: StockLocation
  quantity: number
  expiresAt?: string
  notes?: string
}

const ITS = { supplier: 'Itsmania', supplierPhone: '88968486' }
const MM = { supplier: 'Marcas Mundiales', supplierPhone: '88489820' }
const CER = { supplier: 'Cervecería', supplierPhone: '98120884' }
const PEP = { supplier: 'Pepsi', supplierPhone: '95724003' }
const DIC = { supplier: 'Dicosa Vapes', supplierPhone: '33725048' }

export const STOCK_SEED: StockSeedRow[] = [
  { name: 'Flor de Caña Coco', presentation: '750 ml', category: 'Licores', ...ITS, location: 'BODEGA', quantity: 2 },
  { name: 'Flor de Caña Extra Seco', presentation: '1 L', category: 'Licores', ...ITS, location: 'BODEGA', quantity: 1 },
  { name: 'Flor de Caña 4 años', presentation: '1 L', category: 'Licores', ...ITS, location: 'BODEGA', quantity: 24 },
  { name: 'Flor de Caña 4 años', presentation: '1.75 L', category: 'Licores', ...ITS, location: 'BODEGA', quantity: 3 },
  { name: 'Flor de Caña 4 años', presentation: '750 ml', category: 'Licores', ...ITS, location: 'BODEGA', quantity: 1 },
  { name: 'Flor de Caña 7 años', presentation: '750 ml', category: 'Licores', ...ITS, location: 'BODEGA', quantity: 6 },
  { name: 'Flor de Caña 12 años', presentation: '750 ml', category: 'Licores', supplier: 'Aldo Medina', supplierPhone: '88968486', location: 'BODEGA', quantity: 5 },
  { name: 'Flor de Caña 18 años', presentation: '750 ml', category: 'Licores', location: 'BODEGA', quantity: 3 },
  { name: 'Jack Daniel\'s', presentation: '750 ml', category: 'Licores', location: 'BODEGA', quantity: 2 },
  { name: 'Jägermeister', presentation: '750 ml', category: 'Licores', location: 'BODEGA', quantity: 3 },
  { name: 'Jägermeister', presentation: '1.75 L', category: 'Licores', ...ITS, location: 'BODEGA', quantity: 6 },
  { name: 'Dewar\'s 18 años', presentation: '750 ml', category: 'Licores', location: 'BODEGA', quantity: 3 },
  { name: 'Dewar\'s 12 años', presentation: '750 ml', category: 'Licores', location: 'BODEGA', quantity: 4 },
  { name: 'Tequila Don Julio', presentation: '750 ml', category: 'Licores', location: 'BODEGA', quantity: 1 },
  { name: 'Tequila Cristalino 1800', presentation: '750 ml', category: 'Licores', ...ITS, location: 'BODEGA', quantity: 3 },
  { name: 'Bacardi 8 años', presentation: '750 ml', category: 'Licores', location: 'BODEGA', quantity: 3 },
  { name: 'Buchanan\'s 12 años', presentation: '750 ml', category: 'Licores', ...ITS, location: 'BODEGA', quantity: 4 },
  { name: 'Buchanan\'s 18 años', presentation: '750 ml', category: 'Licores', ...ITS, location: 'BODEGA', quantity: 2 },
  { name: 'Johnnie Walker Blue Label', presentation: '750 ml', category: 'Licores', ...ITS, location: 'BODEGA', quantity: 1 },
  { name: 'Johnnie Walker Gold Label', presentation: '750 ml', category: 'Licores', ...ITS, location: 'BODEGA', quantity: 3 },
  { name: 'Ron Zacapa', presentation: '750 ml', category: 'Licores', location: 'BODEGA', quantity: 5 },
  { name: 'Gin Tanqueray', presentation: '750 ml', category: 'Licores', location: 'BODEGA', quantity: 2 },
  { name: 'Hendrick\'s Gin', presentation: '750 ml', category: 'Licores', location: 'BODEGA', quantity: 3 },
  { name: 'Bombay Gin', presentation: '750 ml', category: 'Licores', ...MM, location: 'BODEGA', quantity: 13 },
  { name: 'Jim Beam Bourbon', presentation: '1 L', category: 'Licores', supplier: 'Rolando', supplierPhone: '88489820', location: 'BODEGA', quantity: 1 },
  { name: 'Cîroc Vodka', presentation: '750 ml', category: 'Licores', location: 'BODEGA', quantity: 1 },
  { name: 'Old Parr 12 años', presentation: '750 ml', category: 'Licores', location: 'BODEGA', quantity: 3 },
  { name: 'Santa Helena Tinto', presentation: '750 ml', category: 'Vinos', ...MM, location: 'BODEGA', quantity: 5 },
  { name: 'Santa Helena Blanco', presentation: '750 ml', category: 'Vinos', ...MM, location: 'BODEGA', quantity: 4 },
  { name: 'Riunite Lambrusco Tinto', presentation: '1.5 L', category: 'Vinos', location: 'BODEGA', quantity: 4 },
  { name: 'Riunite Lambrusco Tinto', presentation: '750 ml', category: 'Vinos', location: 'BODEGA', quantity: 2 },
  { name: 'Sperone Spumante', presentation: '750 ml', category: 'Vinos', location: 'BODEGA', quantity: 2 },
  { name: 'Aperol', category: 'Licores', ...ITS, location: 'BODEGA', quantity: 1 },
  { name: 'Demandis Crème de Café', presentation: '750 ml', category: 'Licores', location: 'BODEGA', quantity: 3 },
  { name: 'Mix de Margaritas', presentation: '1 L', category: 'Mixers', ...ITS, location: 'BODEGA', quantity: 2 },
  { name: 'Mix de Maracuyá', presentation: '1 L', category: 'Mixers', ...ITS, location: 'BODEGA', quantity: 1 },
  { name: 'Mix de Mango', presentation: '1 L', category: 'Mixers', ...ITS, location: 'BODEGA', quantity: 1 },
  { name: 'Mix de Sandía', presentation: '1 L', category: 'Mixers', ...ITS, location: 'BODEGA', quantity: 2 },
  { name: 'Mix de Granadina', presentation: '1 L', category: 'Mixers', ...ITS, location: 'BODEGA', quantity: 5 },
  { name: 'Clamato', category: 'Mixers', location: 'BODEGA', quantity: 1 },
  { name: 'Sangría Don Simón', category: 'Vinos', location: 'BODEGA', quantity: 1 },
  { name: 'Real de Coco', category: 'Mixers', location: 'BODEGA', quantity: 1 },
  { name: 'Leche evaporada', category: 'Otros', supplier: 'Súper', location: 'BODEGA', quantity: 3 },
  { name: 'Leche condensada', category: 'Otros', supplier: 'Súper', location: 'BODEGA', quantity: 7 },
  { name: 'Adrenalina', presentation: '473 ml', category: 'Mixers', ...PEP, location: 'BODEGA', quantity: 60 },
  { name: 'Soda Link', category: 'Mixers', ...PEP, location: 'BODEGA', quantity: 37 },
  { name: 'Canada Dry', category: 'Mixers', ...CER, location: 'BODEGA', quantity: 94 },
  { name: 'Agua tónica Canada', category: 'Mixers', ...CER, location: 'BODEGA', quantity: 14 },
  { name: 'Coca-Cola lata', category: 'Mixers', ...CER, location: 'BODEGA', quantity: 1 },
  { name: 'Bloom Berry Mix', category: 'Mixers', location: 'BODEGA', quantity: 12 },
  { name: 'Bloom Lemon', category: 'Mixers', location: 'BODEGA', quantity: 6 },
  { name: 'Salva Vida', category: 'Cerveza', location: 'BODEGA', quantity: 81 },
  { name: 'Imperial', category: 'Cerveza', location: 'BODEGA', quantity: 120, expiresAt: '2026-10-13', notes: 'Vence 13 octubre' },
  { name: 'Coors Light', category: 'Cerveza', location: 'BODEGA', quantity: 75, expiresAt: '2026-09-30', notes: 'Promo MegaCubetazo · vence 30 sep' },
  { name: 'Miller Draft', category: 'Cerveza', location: 'BODEGA', quantity: 93 },
  { name: 'Corona', category: 'Cerveza', location: 'BODEGA', quantity: 12 },
  { name: 'Corona sin alcohol', category: 'Cerveza', location: 'BODEGA', quantity: 20 },

  { name: 'Penca Kamikaze', category: 'Mixers', location: 'MERMA', quantity: 1 },
  { name: 'Luxury Astoria', category: 'Vinos', location: 'MERMA', quantity: 1 },
  { name: 'Clamato', category: 'Mixers', location: 'MERMA', quantity: 1 },
  { name: 'Pepsi lata', category: 'Mixers', location: 'MERMA', quantity: 24 },
  { name: 'Soda Link', category: 'Mixers', location: 'MERMA', quantity: 1 },
  { name: 'Coca-Cola lata', category: 'Mixers', location: 'MERMA', quantity: 1 },
  { name: 'Imperial', category: 'Cerveza', location: 'MERMA', quantity: 13 },
  { name: 'Barena', category: 'Cerveza', location: 'MERMA', quantity: 28 },
  { name: 'Imperial lata', category: 'Cerveza', location: 'MERMA', quantity: 24 },
  { name: 'Coors Light', category: 'Cerveza', location: 'MERMA', quantity: 175, notes: '120 recién junio 2026' },
  { name: 'Modelo', category: 'Cerveza', location: 'MERMA', quantity: 17 },
  { name: 'Imperial botella', category: 'Cerveza', location: 'MERMA', quantity: 35 },
  { name: 'Miller Lite', category: 'Cerveza', location: 'MERMA', quantity: 79, notes: 'Vencidas junio' },
  { name: 'Cerveza cajas vencidas', category: 'Cerveza', location: 'MERMA', quantity: 17, notes: '17 cajas vencidas' },
  { name: 'Salva Vida', category: 'Cerveza', location: 'MERMA', quantity: 10 },
  { name: 'Ploom 5000', category: 'Vapes', ...DIC, location: 'MERMA', quantity: 5, notes: 'Malos' },
  { name: 'Ploom 5000', category: 'Vapes', ...DIC, location: 'BODEGA', quantity: 4, notes: 'Sellados' },
  { name: 'Ploom 6000', category: 'Vapes', ...DIC, location: 'BODEGA', quantity: 11, notes: 'Sellados' },
  { name: 'Kaelee', category: 'Vapes', ...DIC, location: 'BODEGA', quantity: 5, notes: 'Sellados' },
  { name: 'Vabeen', category: 'Vapes', ...DIC, location: 'BODEGA', quantity: 7, notes: 'Sellados' },

  { name: 'Aperol', category: 'Licores', location: 'ABIERTO', quantity: 2 },
  { name: 'Bourbon', category: 'Licores', location: 'ABIERTO', quantity: 1 },
  { name: 'Mix de Fresa', category: 'Mixers', location: 'ABIERTO', quantity: 1 },
  { name: 'Mix de Granadina', category: 'Mixers', location: 'ABIERTO', quantity: 3 },
  { name: 'Flor de Caña 12 años', presentation: '750 ml', category: 'Licores', location: 'ABIERTO', quantity: 1, notes: 'Marco Bonilla' },
  { name: 'Ron Zacapa Gran Reserva Especial', presentation: '750 ml', category: 'Licores', location: 'ABIERTO', quantity: 1, notes: 'Marco Bonilla' },
  { name: 'Johnnie Walker Black Label 12 años', presentation: '1 L', category: 'Licores', location: 'ABIERTO', quantity: 1, notes: 'Marco Bonilla' },
  { name: 'Old Parr 12 años', presentation: '750 ml', category: 'Licores', location: 'ABIERTO', quantity: 1, notes: 'Marco Bonilla' },
  { name: 'J.P. Chenet', presentation: '750 ml', category: 'Vinos', location: 'ABIERTO', quantity: 1, notes: 'Marco Bonilla' },

  { name: 'Ultra', category: 'Cerveza', location: 'BARRA', quantity: 96 },
  { name: 'Miller Draft', category: 'Cerveza', location: 'BARRA', quantity: 24 },
  { name: 'Salva Vida', category: 'Cerveza', location: 'BARRA', quantity: 168 },
  { name: 'Imperial', category: 'Cerveza', location: 'BARRA', quantity: 24 },
  { name: 'Grey Goose', presentation: '750 ml', category: 'Licores', location: 'BARRA', quantity: 1 },
  { name: 'Absolut', presentation: '750 ml', category: 'Licores', location: 'BARRA', quantity: 5 },
  { name: 'Smirnoff', presentation: '750 ml', category: 'Licores', location: 'BARRA', quantity: 5 },
  { name: 'Smirnoff', presentation: '1 L', category: 'Licores', location: 'BARRA', quantity: 4 },
  { name: 'Buchanan\'s 12 años', presentation: '750 ml', category: 'Licores', location: 'BARRA', quantity: 4 },
  { name: 'Flor de Caña 4 años', presentation: '750 ml', category: 'Licores', location: 'BARRA', quantity: 7 },
  { name: 'José Cuervo', presentation: '750 ml', category: 'Licores', location: 'BARRA', quantity: 2 },
  { name: 'Johnnie Walker Black Label', presentation: '750 ml', category: 'Licores', location: 'BARRA', quantity: 2 },
  { name: 'Flor de Caña 18 años', presentation: '750 ml', category: 'Licores', location: 'BARRA', quantity: 2 },
  { name: 'Tequila Cristalino 1800', category: 'Licores', location: 'BARRA', quantity: 1 },
  { name: 'Aperol', category: 'Licores', location: 'BARRA', quantity: 1 },
  { name: 'Bombay Gin', category: 'Licores', location: 'BARRA', quantity: 1 },
  { name: 'Undurraga', category: 'Vinos', location: 'BARRA', quantity: 1 },
  { name: 'Don Julio', category: 'Licores', location: 'BARRA', quantity: 1 },
  { name: 'Old Parr', category: 'Licores', location: 'BARRA', quantity: 1 },
  { name: 'Flor de Caña 12 años', category: 'Licores', location: 'BARRA', quantity: 2 },
  { name: 'Mix de Fresa', category: 'Mixers', location: 'BARRA', quantity: 4 },
  { name: 'Mix de Mango', category: 'Mixers', location: 'BARRA', quantity: 1 },
  { name: 'Mix de Mora', category: 'Mixers', location: 'BARRA', quantity: 1 },
  { name: 'Mix de Maracuyá', category: 'Mixers', location: 'BARRA', quantity: 1 },
  { name: 'Mix de Granadina', category: 'Mixers', location: 'BARRA', quantity: 1 },
  { name: 'Mix de Manzana verde', category: 'Mixers', location: 'BARRA', quantity: 1 },
  { name: 'Agua tónica', category: 'Mixers', location: 'BARRA', quantity: 23 },
  { name: 'Canada Dry', category: 'Mixers', location: 'BARRA', quantity: 7 },
  { name: 'Coca-Cola lata', category: 'Mixers', location: 'BARRA', quantity: 44 },
  { name: 'Soda lata', category: 'Mixers', location: 'BARRA', quantity: 18 },
  { name: 'Agua botella', category: 'Mixers', location: 'BARRA', quantity: 33 },
  { name: 'Cranberry', category: 'Mixers', location: 'BARRA', quantity: 3 },
]
